---
# This creates the named workspace directory in the users home
workspace: '.myosx'

# Manage your dotfiles
dotfiles:
  manage: true
  repo: 'https://github.com/surminus/dotfiles.git'
  files:
  - ackrc
  - gitconfig
  - vimrc
  - zshrc

# Manage homebrew packages
homebrew:
  manage: true
  packages:
    brew:
      - 'ack'
      - 'autoconf'
      - 'coreutils'
      - 'libgpg-error'
      - 'libassuan'
      - 'libgcrypt'
      - 'libksba'
      - 'pth'
      - 'dirmngr'
      - 'libpng'
      - 'freetype'
      - 'gmp'
      - 'isl'
      - 'mpfr'
      - 'libmpc'
      - 'gcc'
      - 'gdbm'
      - 'gettext'
      - 'git'
      - 'gnu-getopt'
      - 'gnu-tar'
      - 'pinentry'
      - 'gpg-agent'
      - 'libusb'
      - 'libusb-compat'
      - 'gnupg2'
      - 'go'
      - 'hub'
      - 'jpeg'
      - 'libtiff'
      - 'libtool'
      - 'perl'
      - 'xz'
      - 'imagemagick'
      - 'oniguruma'
      - 'jq'
      - 'libyaml'
      - 'node'
      - 'openssl'
      - 'pwgen'
      - 'tree'
      - 'pass'
      - 'pcre'
      - 'pkg-config'
      - 'readline'
      - 'sqlite'
      - 'python'
      - 'ruby-build'
      - 'rbenv'
      - 'rbenv-aliases'
      - 'rbenv-bundler'
      - 'ruby'
      - 's3cmd'
      - 'vim'
      - 'wget'
      - 'zsh'
    cask:
      - 'alfred'
      - 'bittorrent'
      - 'Caskroom'
      - 'facter'
      - 'google-cloud-sdk'
      - 'gpgtools'
      - 'osxfuse'
      - 'puppet'
      - 'tuntap'
      - 'virtualbox'
      - 'vmware-fusion'
      - 'xscreensaver'
    tap:
      - 'caskroom/cask'
